name: uses-foo
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: python based snap 
description: |
    this snap just pulls the most basic python package and uses the
    python plugin to build it

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict 

parts:
  foo:
    # See 'snapcraft plugins'
    plugin: python
    source: https://github.com/dclane-code/foopackage.git

apps:
    foo:
        command: bin/foopackage
